/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'fetch-github-pr': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'analyze-code-ai': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'demo-mode': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'dashboard-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'analyze-pr-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'analytics-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}